spring.application.name=lumievent

spring.datasource.url=jdbc:mysql://localhost:3306/novaticket
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
