spring.application.name=lumievent

spring.datasource.url=jdbc:mysql://localhost:3306/novaticket
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Directorio de subida de imágenes (relativo al directorio de trabajo del proyecto)
app.upload.dir=src/main/resources/static/uploads

# Límites multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
